### ISSUE TITLE
how to reset SoftRF T-Beam for Arduino programming?

### ISSUE THREAD

**Issue by tedder** [Xinyuan-LilyGO/TTGO-T-Beam#1]
Hi, I have a T-Beam from you, it came with SoftRF installed. I know this because I can see the wifi SSID for SoftRF.

The serial port doesn't show up when I connect it to my computers. How do I reset it to be programmed with my own Arduino sketches?

**Comment by lewisxhe** [comment]
Is it resolved? Please confirm that the USB port is valid, then the driver, otherwise there should be a problem with the board @tedder

**Comment by tedder** [comment]
It must be a board problem.
