### ISSUE TITLE
0% equivalent voltage

### ISSUE THREAD

**Issue by SeungRyeol** [Xinyuan-LilyGO/TTGO-T-Beam#6]
I am measuring the voltage of Li-ion battery as calculated by axp.getBattVoltage () / 1000.0.

When the battery is not charging, how much mV should I expect to drop to 0% ?

Tell me the mV equivalent to 0% that the lithium-ion battery will not damage.

**Comment by lewisxhe** [comment]
AXP192 has a register for shutdown voltage. The default setting is 2.9V. If it is lower than 2.9V, it will automatically shut down.

**Comment by SeungRyeol** [comment]
@lewisxhe 
Can I do mapping 4.2mV to 100% and 2.9mV to 0%? Is this appropriate?

**Comment by lewisxhe** [comment]
You can do this, but this will not calculate the battery capacity very accurately

**Comment by SeungRyeol** [comment]
@lewisxhe 
Okay! Thank you!!
